import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

const UPDATED = "6 September 2026";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your use of LaunchRadar — accounts, acceptable use, plans and billing, content ownership, disclaimers and liability.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated={UPDATED} current="/terms">
      <p>
        These terms are a legal agreement between you (and, if you use LaunchRadar for an
        organisation, that organisation) and <strong>IGNISTECH LTD</strong> (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;), a company registered in England and Wales under company number 16892976,
        with its registered office at 21 Winterberry Way, Nantwich, Cheshire, which operates the
        LaunchRadar service (&ldquo;LaunchRadar&rdquo;). By creating an account or using the service
        you agree to them. If you are using LaunchRadar on behalf of an organisation, you confirm you
        are authorised to bind it.
      </p>

      <h2>1. The service</h2>
      <p>
        LaunchRadar analyses a product URL you provide and produces a Growth Score, a prioritised
        backlog of growth tasks, launch plans, search and AI visibility reports, and Opportunity
        Radar results, and drafts related content. Much of this output is generated by AI and may be
        inaccurate, incomplete or out of date. It is provided for your consideration only and is not
        professional marketing, legal, financial or other advice. You are responsible for reviewing
        output and deciding whether and how to use it.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You must provide accurate account information and keep it current. You are responsible for
        activity under your account and for keeping your login credentials secure. Tell us promptly
        at <a href="mailto:launchradar@outlook.com">launchradar@outlook.com</a> if you suspect
        unauthorised use. Accounts are for a single user; do not share a login.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          submit a URL you do not own or have permission to analyse, or use LaunchRadar in a way that
          breaches the target site&rsquo;s terms of use or applicable law;
        </li>
        <li>
          use the service to send spam, harass anyone, infringe intellectual property or privacy
          rights, or post content that is unlawful, deceptive or misleading;
        </li>
        <li>
          copy, resell, sublicense or provide the service to third parties except as expressly
          permitted;
        </li>
        <li>
          reverse engineer, decompile or attempt to extract source code, except to the extent this
          restriction is prohibited by law;
        </li>
        <li>
          probe, scan or test the vulnerability of the service, or circumvent authentication, rate
          limits or plan limits;
        </li>
        <li>
          use automated means to overload the service or interfere with other users.
        </li>
      </ul>

      <h2>4. Opportunity Radar and drafted replies</h2>
      <p>
        Opportunity Radar surfaces publicly posted discussions and can draft a suggested reply.
        LaunchRadar never posts anything for you. If you choose to post a reply, you do so under your
        own account on the relevant platform, you must comply with that platform&rsquo;s rules, and
        you must disclose your connection to the product where the platform or the law requires it.
        You are solely responsible for anything you post.
      </p>

      <h2>5. Plans, billing and renewals</h2>
      <ul>
        <li>
          LaunchRadar offers a free plan and paid plans (Builder and Growth), billed monthly or
          annually in GBP through Stripe.
        </li>
        <li>
          Paid plans renew automatically at the end of each billing period until cancelled. You can
          cancel at any time from the billing portal; cancellation takes effect at the end of the
          current period and you keep access until then.
        </li>
        <li>
          Except where the law requires otherwise, payments are non-refundable and we do not provide
          partial-period refunds. Prices are exclusive of taxes unless stated; applicable taxes are
          added at checkout.
        </li>
        <li>
          We may change plan prices or contents. We will give at least 30 days&rsquo; notice of a
          price increase, which will apply from your next renewal; you can cancel before then if you
          do not accept it.
        </li>
        <li>
          Metered plan limits reset at the start of each calendar month. Access to paid features
          ends when a subscription lapses or is cancelled.
        </li>
      </ul>

      <h2>6. Your content and our intellectual property</h2>
      <p>
        You retain ownership of the URLs and information you submit and of the outputs LaunchRadar
        generates specifically for your projects. You grant us a worldwide, non-exclusive licence to
        host, copy, process and display that content and those outputs as needed to operate the
        service for you and to keep it secure. We and our licensors own the LaunchRadar software,
        interfaces, branding and any aggregated or de-identified insights derived from use of the
        service.
      </p>

      <h2>7. Third-party services</h2>
      <p>
        LaunchRadar relies on Clerk (authentication), Stripe (payments) and Anthropic (AI
        processing). Your use of the service is also subject to those providers&rsquo; terms, and we
        are not responsible for their acts or omissions.
      </p>

      <h2>8. Availability and changes</h2>
      <p>
        The service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We do
        not guarantee it will be uninterrupted or error-free, and we may modify, suspend or
        discontinue features. We will try to give reasonable notice of material adverse changes.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        To the fullest extent permitted by law, we disclaim all warranties, express or implied,
        including fitness for a particular purpose and non-infringement. We do not warrant that
        LaunchRadar will increase your traffic, users or revenue, or that AI-generated
        recommendations are accurate or suitable for your situation.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        Nothing in these terms limits liability that cannot be limited by law, including for death or
        personal injury caused by negligence, or for fraud. Subject to that, we are not liable for
        loss of profits, revenue, goodwill, data or anticipated savings, or for any indirect or
        consequential loss; and our total liability arising out of or relating to the service is
        limited to the greater of the amounts you paid us in the 12 months before the event giving
        rise to the claim, or £100.
      </p>

      <h2>11. Indemnity</h2>
      <p>
        You will indemnify us against claims, losses and reasonable costs arising from your misuse of
        the service, your breach of these terms, the content you submit, or any reply or other
        content you publish based on LaunchRadar&rsquo;s output.
      </p>

      <h2>12. Suspension and termination</h2>
      <p>
        We may suspend or terminate your access if you breach these terms, if required by law, or to
        protect the service or other users. You may stop using LaunchRadar and close your account at
        any time. On termination your right to use the service ends and your data is handled as
        described in the <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>13. Changes to these terms</h2>
      <p>
        We may update these terms from time to time. We will update the &ldquo;last updated&rdquo;
        date and, for material changes, give notice by email or in the app. Continuing to use
        LaunchRadar after changes take effect means you accept them.
      </p>

      <h2>14. Governing law</h2>
      <p>
        These terms and any dispute relating to them are governed by the laws of England and Wales,
        and the courts of England and Wales have exclusive jurisdiction, except that we may seek
        injunctive relief in any competent court.
      </p>

      <h2>15. Contact</h2>
      <p>
        <a href="mailto:launchradar@outlook.com">launchradar@outlook.com</a>.
      </p>
    </LegalPage>
  );
}
